### ISSUE TITLE
Analysis outputs not saved for Cohort, only for sequencing groups.

### ISSUE THREAD

**Issue by vivbak** [populationgenomics/cpg-flow#24]
When you create an analysis object in metamist, you can either pass sequencing group ids or cohort ids (perhaps both). This impacts the base entity that the analysis is stored against, i.e. can you search for your analyses via sgs or via cohorts.

Right now, the cohort IDs are not passed to the appropriate metamist call. So no analyses are linked to the cohorts. 

The fix is somewhere around here:
https://github.com/populationgenomics/cpg-flow/blob/0e104c193a55d319d5d5810103cfd0a4b15e503f/src/cpg_flow/metamist.py#L404-L409

**Comment by violetbrina** [comment]
Solved by PR: https://github.com/populationgenomics/cpg-flow/pull/25
